// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import {
  isMonitoredServiceUrl,
  isServiceFailureStatus,
  reportServiceFailure,
  reportServiceRecovery,
} from '@/lib/serviceAvailability';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const REMEMBER_SESSION_KEY = 'zania:remember-session';

const browserStorage = (type: 'local' | 'session') => {
  if (typeof window === 'undefined') return null;
  return type === 'local' ? window.localStorage : window.sessionStorage;
};

export const shouldRememberSession = () => browserStorage('local')?.getItem(REMEMBER_SESSION_KEY) !== 'false';

export const setRememberSession = (remember: boolean) => {
  browserStorage('local')?.setItem(REMEMBER_SESSION_KEY, String(remember));
};

const sessionStorageAdapter = {
  getItem: (key: string) => (shouldRememberSession() ? browserStorage('local') : browserStorage('session'))?.getItem(key) ?? null,
  setItem: (key: string, value: string) => {
    (shouldRememberSession() ? browserStorage('local') : browserStorage('session'))?.setItem(key, value);
  },
  removeItem: (key: string) => {
    browserStorage('local')?.removeItem(key);
    browserStorage('session')?.removeItem(key);
  },
};

const nativeFetch = globalThis.fetch.bind(globalThis);

const monitoredFetch: typeof fetch = async (input, init) => {
  const requestUrl = typeof input === 'string'
    ? input
    : input instanceof URL
      ? input.href
      : input.url;
  const monitored = isMonitoredServiceUrl(requestUrl, SUPABASE_URL);

  try {
    const response = await nativeFetch(input, init);
    if (monitored) {
      if (isServiceFailureStatus(response.status)) reportServiceFailure('backend');
      else if (response.ok) reportServiceRecovery();
    }
    return response;
  } catch (error) {
    if (monitored) reportServiceFailure(window.navigator.onLine ? 'backend' : 'offline');
    throw error;
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: monitoredFetch,
  },
  auth: {
    storage: sessionStorageAdapter,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
  }
});
